description: The 9th yearly hackathon hosted by University of Edinburgh students.


links:
    register:  https://register.2023.hacktheburgh.com
    volunteer: https://forms.gle/5PdjgsMuLR1uJc1b8
    twitter: https://twitter.com/hacktheburgh
    facebook: https://www.facebook.com/hacktheburgh
    youtube: https://www.youtube.com/channel/UCQKvr90vGzbgteMeM1A9nxQ
    instagram: https://instagram.com/hacktheburgh
