description: The 9th yearly hackathon hosted by University of Edinburgh students.
# register:  none #https://register.2022.hacktheburgh.com
# volunteer: none #https://docs.google.com/forms/d/e/1FAIpQLSejEqfQm5gJX3yWjNBFo1M_rRbnZ13E4B4WFwoe-gsMkZG97A/viewform?usp=sf_link
links:
   
    twitter: https://twitter.com/hacktheburgh
    facebook: https://www.facebook.com/hacktheburgh
    youtube: https://www.youtube.com/channel/UCQKvr90vGzbgteMeM1A9nxQ
    instagram: https://instagram.com/hacktheburgh
